return PlaceObj('ModDef', {
	'title', "Reinforcementest",
	'id', "a7iPvXU",
	'author', "permanent666",
	'version', 674,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"InventoryItem/HUDA_Radio.lua",
		"Code/CA_UseRadio.lua",
		"Code/CA_BombardRemote.lua",
		"Code/CODE_Reinforcements.lua",
		"Code/CODE_MortarStrike.lua",
		"Code/CA_Bombard.lua",
		"Code/CODE_Mortar.lua",
		"Code/CODE_Utils.lua",
		"Code/OR_Bombard.lua",
		"Code/X_Radio.lua",
		"Code/X_Mortar.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1713912531,
	'code_hash', 4261519837115658121,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "HUDA_Radio",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "TextStyle",
			'Id', "HUDA_Radio",
			'ClassDisplayName', "Text style",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "TextStyle",
			'Id', "HUDA_Radio_Bright",
			'ClassDisplayName', "Text style",
		}),
	},
})